### ISSUE TITLE
Update GitHub release with generated notes

### ISSUE THREAD

**Issue by asizikov** [shiftkey/hermes#13]
Once Hermes produced a release notes file/text the next obvious step is to edit [release](https://developer.github.com/v3/repos/releases/) on GitHub.

That will fit into CI/CD pipeline perfectly. The build triggered by tag push can create a package, collect release notes, create release on GitHub and publish an artifact.

**Comment by shiftkey** [comment]
I feel like this is going into the territory of https://github.com/GitTools/GitReleaseManager, and I'd rather not duplicate features if it's easier to just ensure someone else's work fits nicely alongside ours.

**Comment by asizikov** [comment]
I didn't know about this project. 
You can close this issue.
